import "../customize/CustomizeViewComp";
import "../map/MapViewComp";
import "../character/CharacterViewComp";
import "../prebattle/PreBattleViewComp";
import "../battle/BattleViewComp";
import "../result/ResultViewComp";
import "../reward/RewardViewComp";
import "../shop/ShopViewComp";
import "../ending/EndingViewComp";
